### ISSUE TITLE
Scrolling down the table doesn't show complete data

### ISSUE THREAD

**Issue by bsomangnln** [cheton/infinite-tree#21]
Hi,

I'm unable to view all the data when I scroll down. I know I'm missing something, but don't know what, please help. 

Thanks!

**Comment by husanhong3** [comment]
I have the same problem, how did you solve this?

**Comment by bsomangnln** [comment]
Hi husanhong3,

I increased the value of "rowsInBlock" parameter in the file infinite-tree.js.

**Comment by cdeutsch** [comment]
Changing `rowsInBlock` or `blocksInCluster` will work but it's probably not your root issue. You're just displaying more nodes instead of fixing whatever is broken with the virtualization of the nodes.

See https://github.com/cheton/infinite-tree/issues/75#issuecomment-2738418315 for the fixes I needed to do.
